### ISSUE TITLE
Completing atoms blocks the editor for a long time in Deoplete

### ISSUE THREAD

**Issue by hahuang65** [awetzel/elixir.nvim#4] opened 2016-01-11 05:37 UTC
Wondering if you've seen this before, but when I type `:` it blocks for a very long time before returning the completions.

Even if I don't want completion and continue typing, it will just freeze for about a minute then show the rest of my keystrokes.

I'm using this on neovim with deoplete.

**Comment by x-benclarke** [comment] 2016-01-19 19:50
I'm having the same issue using neovim and deoplete.

**Comment by hahuang65** [comment] 2016-01-19 20:04
@x-benclarke I've got a similar issue going on here: https://github.com/Shougo/deoplete.nvim/issues/119

**Comment by hahuang65** [comment] 2016-01-19 23:24
The deoplete maintainer has suggested it is a problem from this repo's code.

https://github.com/Shougo/deoplete.nvim/issues/119#issuecomment-173017766

@awetzel it'd be really great to have this fixed! :)

**Comment by ashervb** [comment] 2016-02-08 01:19
+1 Also having this issue (now that I've got it working - thanks to your help @awetzel)

**Comment by benhamill** [comment] 2016-02-29 06:45
Just wanted to note that this seems to be the same issue as #1. Just some context for those coming after.

According to @shougo, the problem is that https://github.com/awetzel/elixir.nvim/blob/master/rplugin/python3/deoplete/sources/elixir.py#L20 calls a vim function synchronously. I know very little about plugins for Neovim, but... is it reasonable to convert this somehow to an async call?

**Comment by benhamill** [comment] 2016-02-29 07:07
Alternatively, @awetzel, would it be possible to make https://github.com/awetzel/elixir.nvim/blob/master/rplugin/python3/deoplete/sources/elixir.py#L17 respect `g:deoplete#auto_completion_start_length`? Omitting that attribute should do it. Or maybe making a config specific to this plugin to override it?

The fix being to edit the plugin source is kind of sketchy.

**Comment by awetzel** [comment] 2016-03-04 20:40
yes it would be nice, you are right about the editing it should be a conf option...
My proposal is to add the conf option to the Elixir Autocomplete function. I am doing it right now !
Sorry for the very late answer

**Comment by awetzel** [comment] 2016-03-05 01:56
@benhamill @exitface : 
The last 3 improvements may improve your deoplete experience : 
- maintain a cache of `Code.get_docs/2` results into an ets table because it is very slow
- handle a "minimum string length" (`g:elixir_comp_minlen`) configuration for allowed completion
- handle a "maximum document with inline preview" in completion (`g:elixir_maxpreviews`) because when you have to many results, then you will never read all the inline documentation. And as they are slow to query, it is nice to do that :)

**Comment by awetzel** [comment] 2016-03-05 01:59
With these improvements, even with `g:elixir_comp_minlen` == 0, the behaviour is acceptable in my environment (without deoplete actually), please tell me if it is better for you.

Use `/path/to/elixir.nvim/install.sh` to clone the last plugin version and recompile it

**Comment by benhamill** [comment] 2016-03-05 06:04
I think this is a reasonable interim solution. Where does the `ElixirComplete` function come from? Could it be replaced with a Python function as mentioned by @shougo in [the related Issue on deoplete](https://github.com/Shougo/deoplete.nvim/issues/119#issuecomment-192556555)?

**Comment by benhamill** [comment] 2016-03-05 06:15
Also... it looks like you updated the README, but not the code... was that intentional...?

**Comment by awetzel** [comment] 2016-03-05 11:48
The "real" plugin is actually in Elixir in the repo https://github.com/awetzel/nvim-rplugin , which is running in Neovim thanks to my host plugin : https://github.com/awetzel/neovim-elixir
`elixir.nvim` is an "umbrella" repo and `install.sh`
clones and build then host plugin and the elixir plugin.

So the three commits are : 
- https://github.com/awetzel/nvim-rplugin/commit/3593bded62d3486777570cd7ed2275f975e5bfe8
- https://github.com/awetzel/nvim-rplugin/commit/b41c31b993e65af8666df9e028f3e0c3d04d408a
- https://github.com/awetzel/nvim-rplugin/commit/0f1ce8862b7d5cc884586b1fd3734612bad88eb5

So no it cannot be replaced with any Python function since it is actually an elixir one : 
https://github.com/awetzel/nvim-rplugin/blob/master/lib/rplugin.ex#L89-L136

As I mentionned in my previous comment, run : `/path/to/elixir.nvim/install.sh` to update your install : clone the last plugin version and recompile it

**Comment by awetzel** [comment] 2016-03-05 12:01
The solution I made is a faster function which makes all possible tricks (cache, limits) to get around the very slow `Code.get_docs/2` elixir function which is the real problem here, so it is not meant to be an interim solution. Omnicompletion is synchronous in Vim.

**Comment by awetzel** [comment] 2016-03-05 15:39
Last trick : parallel retrieval by chunks of completion documentation, and I think I cannot make more : 
the completion now is only slow when `IEx.Autocomplete.expand` is slow (more exactly on module completion with many modules and erlang `:code.all_loaded` being slow.

Tell me if it improves your case and I close the issue . 

And of course thank you very much for your review :)

**Comment by ashervb** [comment] 2016-03-07 00:43
@awetzel Works great for me now, thank you!

**Closed as completed** 2016-03-07 09:09 UTC
